### ISSUE TITLE
Date string validation not strict enough when pressing 'enter'

### ISSUE THREAD

**Issue by embrown0482** [blackbaud/skyux-datetime#101]
### Expected behavior

The following strings should be invalid dates. Behavior should be consistent whether tabbing out of input or pressing enter

Example invalid dates:
- 13/11/2019
- 20/12/2030
- 32/11/2030

### Actual behavior

- 13/11/2019   => Date is converted to 11/20/2013 and accepted as valid
- 20/12/2030   => If Enter is pressed, date is accepted as valid
- 32/11/2030   => If Enter is pressed, date is accpted as valid 

### Steps to reproduce

1. Navigate to: https://developer.blackbaud.com/skyux/components/datepicker
2. Input each example date manually 
3. Press Enter instead of tabbing or clicking out

**Comment by Blackbaud-AlexKingman** [comment]
Some more info...

It looks like the root cause is the internal formatter (`SkyDateFormatter`) attempts to format the provided string as an ISO date if the first attempt is invalid:
```
    if (!momentValue.isValid()) {
      momentValue = moment(dateString, 'YYYY-MM-DDThh:mm:ss.sssZ');
    }
```

Since this is not using moment's "strict formatting", the string will accept a variety of entries and convert them to an ISO date, which will result in a valid date. For example, user input `13/11/2019` will turn into `2013-11-20`.

**Comment by Blackbaud-AlexKingman** [comment]
As to not introduce a breaking change, we're going to add an optional input property for strict formatting mode. This change will still keep the nicety of matching both format and ISO format, but will give consumers the option to enforce a strict match on formatting. If no match is found in this latter case, a validation error will be thrown.

**Comment by embrown0482** [comment]
Thanks for following up on this Alex! I do think the line you mentioned is the culprit, however the scenario 13/11/2019 still seems unresolved (using default MM/DD/YYY format).

I think what we would like is the ability to only validate against the provided format without falling back to the YYYY-MM-DD format. I understand if that line needs to be kept for backwards compatability but would it be possible for "strict" to also not fallback to a format not provided/expected?

Something like 
```
    if (!strict && !momentValue.isValid()) {
      momentValue = moment(dateString, 'YYYY-MM-DDThh:mm:ss.sssZ');
    }
```

**Comment by Blackbaud-AlexKingman** [comment]
@embrown0482 I'm not sure I understand what you mean by "still seems unresolved"? I just ran a test against latest `master` branch with the following datepicker setup:
```
    <sky-datepicker>
      <input
        formControlName="selectedDate"
        skyDatepickerInput
        type="text"
        [strict]="true"
        [dateFormat]="MM/DD/YYYY"
      />
    </sky-datepicker>
```
If I enter `13/11/2019` into the text input, the form control's `valid` property becomes `false`. I was under the impression this was the bug you were trying to mitigate. Am I not understanding your scenario?

**Comment by embrown0482** [comment]
My mistake, I had put strict on the datepicker not the input!

**Comment by Blackbaud-AlexKingman** [comment]
No worries. Glad to hear its working! :)
