### ISSUE TITLE
Fuzzy date picker > Incorrectly formatted date shouldn't be cleared on field blur.

### ISSUE THREAD

**Issue by Blackbaud-MarybelArcher** [blackbaud/skyux-datetime#109]
### Expected behavior
After entering incorrectly formatted date and leaving field, original input value should not be cleared. The user should be allowed to set the element back to valid value by clearing the original input manually, when the element value is not required.
### Actual behavior
After entering incorrectly formatted date and leaving field, the original input value is cleared, while the element remains invalid. Doing this for optional date fields confuses users, because there is no indication that any valid date needs to be selected and, subsequently deleted to set the element back to valid.
### Steps to reproduce
1. Enter '1111111111111' for date value.
2. Tab out or otherwise leave the date field. Validation will run, element will be marked invalid and provided value will be cleared out.
3. There is no indication that a valid date needs to be selected and subsequently deleted to set the element back to valid.

### Severity
User unfriendly. Increases exponentially the time required to fill out a form while user tries to figure out how to get rid of the 'error' without entering a date the user doesn't have.
### Impact
Impacts forms with optional dates.

**Comment by Blackbaud-SteveBrush** [comment]
@Blackbaud-MarybelArcher Do you mind sharing the version of `@skyux/datetime` your app is using?

**Comment by Blackbaud-MarybelArcher** [comment]
@Blackbaud-SteveBrush We are using "@skyux/datetime": "^3.6.1".

**Comment by Blackbaud-IsaacAggrey** [comment]
Specifically, the fuzzy date picker if the title can be updated.

**Comment by Blackbaud-AlexKingman** [comment]
Hey @ Blackbaud-MarybelArcher thanks for the submission! We agree - the invalid value getting cleared from the input is definitely a bug. We're working on a fix now.

As for the latter point, I'm hesitant to make the directive retain the current model and return it once the input is cleared out. Consumers should be able to make that distinction for themselves, so they could also support scenarios in which they would allow users to submit empty values. I'm hesitant to enforce that across the board.

We'll get to work on the former issue and get this released soon. Thanks!
