### ISSUE TITLE
Fuzzy datepicker (possibly normal datepicker) autocompletes to years in the future

### ISSUE THREAD

**Issue by blackbaud-conorwright** [blackbaud/skyux-datetime#138]
### Expected behavior
if I type in 2/19/68, I would expect it to autocomplete to 2/19/1968 since 2068 is in the future.

### Actual behavior
if I type in 2/19/68, it autocompletes to 2/19/2068

### Additional info
It seems that all years that haven't happened yet (2021-2099) do not autocomplete the same way. I would prefer that future dates complete to dates that have happened a century ago, but would also just accept consistency.

Right now 21-68 autocomplete to 20XX and 69-99 autocomplete to 19XX which feels really weird.
I'm guessing it could be something with the JS Epoch since that edge is pretty dang close to 1970 if that helps debug the issue.

**Comment by Blackbaud-TommyVernieri** [comment]
I'm not sure what the behavior _should_ be but this helps to explain the current behavior at least.

https://momentjs.com/docs/#/parsing/string-format/

> Parsing two digit years
> 
> By default, two digit years above 68 are assumed to be in the 1900's and years 68 or below are assumed to be in the 2000's. This can be changed by replacing the moment.parseTwoDigitYear method. The only argument of this method is a string containing the two years input by the user, and should return the year as an integer.
> 
> moment.parseTwoDigitYear = function(yearString) {
>     return parseInt(yearString) + 2000;
> }
> 

https://github.com/blackbaud/skyux-datetime/blob/09954cc6388eaaf259d1d2f2fc27d2b96d501b0e/src/app/public/modules/datepicker/fuzzy-date.service.ts#L257
