### ISSUE TITLE
Fuzzy date formatter returns incorrect values for dates that don't exist in the current month

### ISSUE THREAD

**Issue by Blackbaud-CoreyArcher** [blackbaud/skyux-datetime#178]
### Expected behavior
When using the Fuzzy Date pipe on arbitrary data, The date is displayed correctly.

### Actual behavior
When trying to display a date where the number of the day is greater than the number of days in the current month, the date is displayed incorrectly.

### Steps to reproduce
During months where there are less than 31 days:
- Add a Fuzzy Date pipe to a page with a Fuzzy Date value of the 31st of some month.
- Observe that the displayed date shows the 1st of that month.

**Comment by Blackbaud-TrevorBurch** [comment]
In `4.1.1`
