### ISSUE TITLE
Date Pipes: Update the API to format Dates without time more easily

### ISSUE THREAD

**Issue by ThomasOrtiz** [blackbaud/skyux-datetime#180]
### Expected behavior
I should be able to format a **Date without a concept of time** easily without jumping through hoops. 
- Example of date without time: `2020-05-11T00:00:00Z`
- Ideally, the API could match with [Angular's Date Pipe](https://angular.io/api/common/DatePipe#parameters) API where they have a `timezone` parameter.
  - `{{ '2020-05-11T00:00:00Z' | date:'shortDate':'UTC' }}`

### Actual behavior
With the Sky Date pipes there isn't an easy/simple way to parse the date as a timeless date. 

### Impact

In **Sky** you have to jump through hoops to get the desired behavior. While these below options work it leads to a lot of repeat/duplicated code across SPAs when this could be first class in the Sky Date Pipe's API. 
1. Create extra pipes to parse the Date into a "UTC" date.
2. Parse my date into another object - SkyFuzzyDate - in order to use `skyFuzzyDate`. 
   - Internally this uses **moment** which has different formatting results from `skyDate`; to have consistency this means we have to pipe `skyFuzzyDate`'s result into `skyDate`. I have an example of this below.

### Steps to reproduce
[Stackblitz link](https://stackblitz.com/edit/localization-examples)

![image](https://user-images.githubusercontent.com/10877317/85448108-5b386100-b564-11ea-9dc3-a6b44edb4727.png)

**Comment by Blackbaud-SteveBrush** [comment]
@Tdortiz So essentially you want us to add a timezone parameter to the `skyDate` pipe?

**Comment by Tdortiz** [comment]
Yea, adding a **timezone** parameter to match Angular's Date Pipe API is ideally what I want.

**Comment by Tdortiz** [comment]
@Blackbaud-SteveBrush Idk if the **Date Pipe** code is using the **INTL API** at its core like the **Numeric Pipe** but if it is it looks like [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat) has a timezone option.

![image](https://user-images.githubusercontent.com/10877317/85618725-3230d280-b62f-11ea-9584-4603ea9a1269.png)

**Comment by Blackbaud-SteveBrush** [comment]
Thanks for the extra info!
