### ISSUE TITLE
SkyDate pipe should allow for non-Date input values 

### ISSUE THREAD

**Issue by Blackbaud-NickGlyder** [blackbaud/skyux-datetime#183]
The SkyDate transform method should support at least `Date` and `string` types to prevent compilation errors in SPA's converting to SkyUX4. The new AoT compilation template checks will throw errors for type mismatches, but `string` is a perfectly valid input for the underlying `moment` implementation.

https://github.com/blackbaud/skyux-datetime/blob/9a6a5a739fa3df6c8724ce59ac74d94995ce4493/src/app/public/modules/date-pipe/date.pipe.ts#L69-L81

## Expected Behavior 
```ts
public dateStringISO: string = (new Date()).toISOString();
public date: Date = new Date();
```

```html
<span> {{ dateStringISO | skyDate }} </span>
<span> {{ date | skyDate }} </span>
```

The above code should compile without error during `skyux build`. 

## Actual Behavior
The string example above fails to compile due to a type mismatch.

## Impact
While there are workarounds, large SPAs can potentially have quite a few string dates that would need to be translated. This is a lot of extra RXJS or controller code, which should be minimized for a first pass conversion to reduce the error surface. 

HTTP contracts are of particular note for this bug, because they should never use data members of type `Date` since that is not a supported JSON type.

**Comment by Blackbaud-TrevorBurch** [comment]
In `4.1.2`
