### ISSUE TITLE
SkyDatepickerConfigService not exported

### ISSUE THREAD

**Issue by blackbaud-joshlandi** [blackbaud/skyux-datetime#204]
### Expected behavior
Should be able to use `SkyDatepickerConfigService` as docs suggest.

### Actual behavior
Cannot since the type is not exported on the `public_api.ts` file.

### Steps to reproduce
Add `SkyDatepickerConfigService` to the constructor of any component and try to serve your SPA.  There will be errors because it gets imported from `@skyux/datetime/modules/datepicker/datepicker-config.service`

### Severity
If there's an alternative to getting `dateFormat` it's not so severe.  Otherwise, the service is used quite a bit for our team and it prohibits us from moving to skyux4.

### Impact
Not sure.  I know our team uses it in a few libraries, but i'm unsure how many more teams use it beyond us.  

[AB#1549617](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1549617)

**Comment by Blackbaud-AlexKingman** [comment]
Fixed in `4.2.0`.
