### ISSUE TITLE
Create a custom `SkyDatePipe`

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux-datetime#21]
Create a custom pipe to handle localized dates asynchronously (Angular's `DatePipe` only supports synchronous locale setup).

The pipe should also work flawlessly with SKY UX's native `SkyAppLocaleProvider` service.

**Comment by Blackbaud-TrevorBurch** [comment]
In `skyux/datetime@3.1.0`

**Comment by Blackbaud-IsaacAggrey** [comment]
Related issue: https://github.com/blackbaud/skyux2/issues/1660
