### ISSUE TITLE
sky-date-range-picker custom option id issue

### ISSUE THREAD

**Issue by abhishekmaheshwari1106** [blackbaud/skyux-datetime#210]
### Expected behavior
When we add a custom option in sky-date-range-picker the ID of the same should remain constant when we select the option.
### Actual behavior
I'm using sky-date-range-picker wherein I have added a custom option, and I'm using this on a sky-modal (filter modal). Now when I'm opening the modal for the first time it generates an id for the custom option that I have added as 1000, but when I close the modal and reopen it again and select the custom option it now changes id to 1001 and increases every time I reopen it.
![image](https://user-images.githubusercontent.com/61449153/90490182-f19b9400-e15b-11ea-92cb-d5a86838fd73.png)

**Comment by Blackbaud-SteveBrush** [comment]
@abhishekmaheshwari1106 Could you explain why you need the ID to be consistent? Can you not just pull the ID from the calculator instance?
See: https://developer.blackbaud.com/skyux/components/date-range-picker#code
```
const calculator = this.dateRangeService.createCalculator({
      shortDescription: 'Since 1999',
      type: SkyDateRangeCalculatorType.Relative,
      getValue: () => {
        return {
          startDate: new Date('1/1/1999'),
          endDate: new Date()
        };
      }
    });

const id = calculator.calculatorId;
```

**Comment by abhishekmaheshwari1106** [comment]
Thanks a lot, that helped.
