### ISSUE TITLE
Chrome Autofill throws error when date time picker present on page.

### ISSUE THREAD

**Issue by MathiasSpicer** [blackbaud/skyux-datetime#213]
When I try to use chrome autofill on a text field, if a date time picker is present on the same page, I get an error about the event key being null.

I believe this is an error in datepicker.component.ts in this block:

```
  private addTriggerButtonEventListeners(): void `{`

    fromEvent(window.document, 'keydown')

      .pipe(takeUntil(this.ngUnsubscribe))

      .subscribe((event: KeyboardEvent) => {

        const key = event.key.toLowerCase();

        if (key === 'escape' && this.isOpen) {

          this.closePicker();

        }

      });

  }

```

The block looks like it is checking to see if escape is pressed, but it seems that when a Chrome autofill event happens the key is null, causing this block to throw an error and then navigate me to the broken bird page. I believe if the code is changed to check for null before calling toLowerCase the problem will be solved.

[AB#1564754](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1564754)

**Comment by Blackbaud-KrisMahon** [comment]
We are hitting the same issue too.  The same issue exists for the time picker.  The same issue was just fixed in the Lookup component last week.  It seems that Chrome's new autofill functionality has broken any SKYUX component that follows the pattern of `event.key.toLowerCase()` without first checking to see if `event.key !== undefined`.  A quick search of SKYUX code for `".key.toLowerCase()"` shows the following SKYUX components may also have this issue still:
- skyux-tiles
- skyux-popovers
- skyux-colorpicker
- skyux-grids

**Comment by Blackbaud-KrisMahon** [comment]
This was closed 2 days ago, but I don't see a new package version released yet.  Any idea when it will be available?

**Comment by Blackbaud-SteveBrush** [comment]
Did `4.5.0` fix this?

**Comment by Blackbaud-AdamBuehler** [comment]
No.  I had been getting the error for Datepicker and Timepicker.  4.5.0 fixed it for the Datepicker, but not Timepicker.

**Comment by Blackbaud-SteveBrush** [comment]
Sounds good; I'll get a fix out for the timepicker today.

**Comment by Blackbaud-AdamBuehler** [comment]
Cool.  Let me know if I can help in anyway.

**Comment by Blackbaud-KrisMahon** [comment]
I haven't tried 4.5.0 yet (but sounds like it works only for DatePicker), but the changelog didn't mention this issue being fixed, which is why I asked about it.  It would be helpful to update the changelog for bug fixes, and also update the issue with the fixed in version.
