### ISSUE TITLE
Date objects with miliseconds over .59 break validation in the DatePicker

### ISSUE THREAD

**Issue by IsaacBoy** [blackbaud/skyux-datetime#223]
### Expected behavior
When setting the DatePicker to some value (say "2020-09-11T18:35:25.62") the date picker would render as "9/11/2020"

### Actual behavior
It breaks validation
https://files.slack.com/files-pri/T02BBN218-F01AX4SNY2D/image.png
![image](https://user-images.githubusercontent.com/8832426/92964620-6ce22400-f442-11ea-9456-aaea2cb2f009.png)

### Steps to reproduce
Set the date picker to "2020-09-11T18:35:25.62". Now notice "2020-09-11T18:35:25.59" works fine

### Severity
Medium?

### Impact
Medium?

[AB#1577051](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1577051)

**Comment by IsaacBoy** [comment]
on @skyux/datetime 4.5.1

**Comment by IsaacBoy** [comment]
I tried to look into this a bit, but as far as I can tell (from testing in a sandbox) [this logic](https://github.com/blackbaud/skyux-datetime/blob/9c18a165ea54eca1937802c3c62226c89a892126/src/app/public/modules/datepicker/datepicker-input.directive.ts#L529) should pass with the inputs above

**Comment by Blackbaud-DanMiller** [comment]
@IsaacBoy - can you provide us with a user scenario in which this is necessary? Could the milliseconds be truncated client-side before entering it into the datepicker?

**Comment by IsaacBoy** [comment]
Sure the input **_could_** be shaped to fix whatever logic this control is using to validate, but that seems like sort of an unnecessary hassle? Especially when the control seems like its supposed to be able to handle valid ISO 8601 datetime values.

So the scenario where this would be necessary is if you bound this control to any Date value that happens to be over .59 milliseconds.

So for example, if this control was bound to some `Date` property (let's call it `value`) and you set `this.value = new Date()` , this would _**seemingly randomly**_ fail the control's validation depending on when that code actually executed. Seems like a non-desired behavior if its something trivial in the control's validation that could be fixed, imho

**Comment by Blackbaud-AlexKingman** [comment]
@IsaacBoy We're taking a look to see if this is a strange nuance with `datetime` or `moment`. We'll get back to you soon.

**Comment by Blackbaud-AlexKingman** [comment]
This should be fixed in `@skyux/datetime@4.5.2`. Please let us know if you have any more trouble!
