### ISSUE TITLE
Timepicker: reactive form control value is not correct on initialization

### ISSUE THREAD

**Issue by Blackbaud-LouisPujol** [blackbaud/skyux-datetime#234]
I have a reactive form using a skyux timepicker component. When I initialize the component I need to check the form to see if it is valid on initialization. To do this I need to get the value from the timepicker component, however, the value is not the object that has the iso8601, hour, minute, etc fields. Instead it is the time value string that I passed in to the form control. At what point are we able to get back the correct object from a form control value tied to a skyux timepicker?

### Steps to reproduce
Using the StackBlitz link for the timepicker component page:
Add a method that does the following: console.log(this.reactiveForm.controls['time'].value);
Call that method during ngOnInit and ngAfterViewInit.
It logs '2:45' to the console.

Add a button on the html that calls that method.
Push the button.
It logs the object {hour: 2, minute: 45, meridie: "AM", timezone: -5, iso8601: Wed Oct 07 2020 02:45:00 GMT-0500 (Central Daylight Time), …} to the console.

### Severity
High because we cannot get the value for a reactive form control when initializing. ngAfterViewInit should be a safe place to check these values because the view should have already finished initializing, however, it seems that the timepicker component is still doing work in this lifecycle.

[AB#1595546](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1595546)

**Comment by johnhwhite** [comment]
The form control value should now be initialized before `ngAfterViewInit` call. #253 

Closing.
