### ISSUE TITLE
Consider abcd3 an invalid date

### ISSUE THREAD

**Issue by Blackbaud-ColbyWhite** [blackbaud/skyux-datetime#25]
### Expected behavior

the input `abcd3` should not be considered a valid date.

### Actual behavior

the input `abcd3` is converted to `03/01/2019` and considered valid

### Steps to reproduce

type in `abcd3` in the [demo](https://developer.blackbaud.com/skyux/components/datepicker)

### Impact

Anybody requiring validation on the date is allowing improper dates.

**Comment by Blackbaud-ColbyWhite** [comment]
After some investigations and some talks with @Blackbaud-SteveBrush, i'm rethinking this ticket. What is fundamentally happening is that we are using `moment` to parse a string from the user and assuming it's in a certain format. However, there is no way to know what format a user is going to type in. And the way `moment` handles the _abcd3_ scenario is take a wild guess since it doesn't exactly match the format. It appears that the native `Date` has somewhat similar behavior. 

So I'm not sure this is a _bug_ per se, but a misuse of `moment`. We don't know the format of what the user is typing in, thus I'm not sure we know how to parse it.

So I propose that we close this and focus the larger UX question of "What is the SKY UX pattern for user input of a date?" The answer to that question I think would solve this "bug" since the answer will mean we will know the format of what the user is typing in.

I will leave it to @blackbaud/skyux-ux to close this story if they deem that an appropriate answer.

**Comment by Blackbaud-SteveBrush** [comment]
Thanks @Blackbaud-ColbyWhite. After talking some more about this, it seems that we can chalk this up to "JavaScript unfortunately handles dates this way", as `moment` is really just passing the input to JavaScript's native `Date` constructor. If you look at Angular Material's date picker component, it behaves in much the same way.
