### ISSUE TITLE
Datepicker is constrained by modal in iOS

### ISSUE THREAD

**Issue by Blackbaud-RobertDixon** [blackbaud/skyux-datetime#33]
A <sky-datepicker> in a modal is covered up by the modal footer in SKYUX2 on an iOS browser. Duplicated on an iPhone X in the following image:
![iOS datepicker bug](https://user-images.githubusercontent.com/25301661/56532903-aef48800-6524-11e9-8940-b10f8096dc21.png)

The HTML for the datepicker was pretty straightforward:

   ```<span>
              <sky-datepicker #endDatePicker>
                  <input
                      [ngModel]="endDate | date:'shortDate'"
                      (ngModelChange)="endDateChange($event)"
                      [skyDatepickerInput]="endDatePicker"
                      #date="ngModel"
                      [minDate]="startDate"
                      [startingDay]="startingDay"
                      required>
              </sky-datepicker>
          </span>
      </div>
  </sky-modal-content>
  <sky-modal-footer>
      <button type="button" class="sky-btn sky-btn-primary" (click)="save()">
        {{ 'apply_button' | skyAppResources }}
      </button>
      <button type="button" class="sky-btn sky-btn-link" (click)="instance.cancel()">
        {{ 'cancel_button' | skyAppResources }}
      </button>
  </sky-modal-footer>
```

And here's the relevant CSS:
```
.date-picker-container {
    padding-top: 10px;
}

.date-picker-container span {
    display: inline-block;
}
```

This issue was reported through a client bug, originally related to an issue I posted relating to the `sky-dropdown` component:
https://github.com/blackbaud/skyux-popovers/issues/15

**Comment by Blackbaud-AlexKingman** [comment]
We found this issue was being exacerbated by a `position: relative` CSS declaration in the consuming SPA. Consumer is diving deeper to determine the need for this style.

**Comment by Blackbaud-AlexKingman** [comment]
We found there was a conflicting `position: relative` on the consumer code that was conflicting with the modal's positioning. Removing that has fixed this issue. Closing ticket.
