### ISSUE TITLE
datepicker dropdown window shoudn't resort days of the week based on the 1st day of the month

### ISSUE THREAD

**Issue by Blackbaud-ToddRoberts** [blackbaud/skyux-datetime#39]
### Expected behavior
Date picker dropdown is always laid out from Sunday to Saturday.

### Actual behavior
Dropdown is resorting days of the week to make the 1st of the month the top  left value.

![image](https://user-images.githubusercontent.com/13765813/57031754-8ea88580-6c16-11e9-8804-9d750ec496c6.png)

### Steps to reproduce
Check the demo

### Severity
High

### Impact
Usability issue

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.2.3`
