### ISSUE TITLE
Datepicker and Timepicker should use similar "selected state" styling to checkboxes/radios

### ISSUE THREAD

**Issue by Blackbaud-AdamFunderburk** [blackbaud/skyux-datetime#40]
![image](https://user-images.githubusercontent.com/15896944/57033692-8d2d8c00-6c1b-11e9-8817-c71ecf7f1913.png)

![image](https://user-images.githubusercontent.com/15896944/57033701-91f24000-6c1b-11e9-9e37-3619a4a2afd6.png)

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.2.5`
