### ISSUE TITLE
Unable to use SkyDatePipe in typescript code

### ISSUE THREAD

**Issue by blackbaud-GavinNicol** [blackbaud/skyux-datetime#57]
### Expected behavior

The DatePipe provided by angular can be injected into a component or service and used to format dates. I would expect that the SkyDatePipe should also have that support.

### Actual behavior

Injected the SkyDatePipe into a service leads to this error `NullInjectorError: No provider for SkyDatePipe!` adding the SkyDatePipe to our providers manually then leads to this error `NullInjectorError: No provider for ChangeDetectorRef!`

### Steps to reproduce

1. Install the skyux/datetime package
2. Add the `SkyDatePipe` class to your constructor
3. Notice the ` NullInjectorError: No provider for SkyDatePipe!`
4. Add `SkyDatePipe` to your providers array
5. NullInjectorError: No provider for ChangeDetectorRef!

StackBlitz: https://stackblitz.com/edit/angular-qoc8nd

### Severity
Low

### Impact
When upgrading to SkyUX3, date formatted using the DatePipe in code may not have the same formatting as before.

**Comment by Blackbaud-SteveBrush** [comment]
Thanks for reporting this bug! Looks like we're not importing the `SkyI18nModule`. I'll take a look right away.

**Comment by blackbaud-elizabethsmith** [comment]
@Blackbaud-SteveBrush the `NullInjectorError: No provider for ChangeDetectorRef!` issue is still occurring when including `SkyDatePipe` in the providers array.

**Comment by blackbaud-elizabethsmith** [comment]
It's also probably worth mentioning again: we are specifically encountering the problem when trying to use SkyDatePipe in a skyux lib, not a spa.
