### ISSUE TITLE
Cannot create an inline datepicker

### ISSUE THREAD

**Issue by thatoddmailbox** [blackbaud/skyux-datetime#60]
It currently doesn't seem possible to create a `sky-datepicker` component that's inline with the rest of the document. There's no technical limitation for this, and if you try adding a `display: inline-block;` to the outermost `.sky-datepicker` div, it appears to function. The only issue is that this seems to require using the [deprecated `::ng-deep` selector](https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep) and is a bit of a hack, so it would be nice if there were a supported way to apply this style.

**Comment by Blackbaud-AlexKingman** [comment]
Thanks for submitting, @thatoddmailbox. Would you be willing to share your specific scenario? Depending on what you're trying to do, there may be better ways to achieve this.

**Comment by Blackbaud-BobbyEarl** [comment]
Here's a Stackblitz showing @Blackbaud-AlexKingman's suggestion.  https://stackblitz.com/edit/angular-hszlig

**Comment by thatoddmailbox** [comment]
I thought I tried that earlier, but I tried again and it looks like it's working now, thanks for the help! This is the UI that I'm trying to create:
![image](https://user-images.githubusercontent.com/1904587/59371371-d7be2000-8d12-11e9-85a6-cbe6041e4581.png)

I'm not sure if there's an easier way than `display: inline-block`. The only alternatives I can think of would be a `sky-fluid-grid` (which would be somewhat messy and wouldn't position the datepicker right next to the "Week of" text) or `float: left;` (which wouldn't be much better)

**Comment by Blackbaud-AlexKingman** [comment]
Workaround provided. Closing.
