### ISSUE TITLE
clicking 'Done' does not close the time selection menu

### ISSUE THREAD

**Issue by Blackbaud-AlexanderVaky** [blackbaud/skyux-datetime#9]
### Expected behavior
When using the time picker as a part of a reactive form, when I select a value and click `Done` I expect the drop down time selection menu to disappear and my value to show in the input.
### Actual behavior
The drop down menu does not go away and stays open.  I have to click off of the menu for it to disappear.
### Steps to reproduce
Create a reactive form which has a time picker component as one of its form controls.
### Severity
Medium
### Impact
Low

**Comment by Blackbaud-SteveBrush** [comment]
Cannot reproduce. Maybe this has been fixed in later versions?
