### ISSUE TITLE
Tabbing into and out of required datepicker does not mark field as invalid

### ISSUE THREAD

**Issue by Blackbaud-ErikaMcVey** [blackbaud/skyux-datetime#93]
### Expected behavior
If you tab into a required datepicker field, do not select a date, and tab out, the field should be in a red error state and marked as "required" just like if you clicked in and out of a required datepicker.

### Actual behavior
Tabbing in and out of a required datepicker leaves the field in a valid state. If it was previously invalid and you tab in and out without selecting a value it is changed to valid.

It seems like this was introduced in 3.6.2 which included these changes https://github.com/blackbaud/skyux-datetime/pull/76.

**Comment by Blackbaud-SeanStephens** [comment]
Possibly related: Entering an out of range date manually in the datepicker field and pressing Enter does not appear to cause the validator to run. The field does not turn red, and form.invalid is not true.

Clicking out of the field after typing in a bad date works as expected.

If I add a validator to the form control, IT will run, so I would imagine a workaround is to perform date validation in an added validator.
